name: Build Package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
   build:
    uses: avantipoint/workflow-templates/.github/workflows/dotnet-build.yml@master
    permissions:
      statuses: write
      checks: write
    with:
      name: AlohaKit
      solution-path: ./src/AlohaKit
      install-workload: maui
      run-tests: false